import { app, ipcMain, shell } from 'electron'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import type { AttentionPrefs, UpdatePrefs } from '../../shared/types'
import { CH } from '../../shared/contract'
import { setAttentionPrefs, setUpdatePrefs, setZoom } from '../config'
import { appInfo } from '../updates'
import { asAttentionTone } from '../attention-core'
import type { Services } from '../services'
import { applyWindowFloor, externalUrl, takePendingOpen } from '../window'
import { asAttentionFocus } from './guards'

/** The app itself: about, updates, the window's zoom, links out, and the attention desk. */
export function registerAppHandlers(s: Services): void {
  const { updates, desk } = s

  ipcMain.handle(CH.appInfo, () => appInfo())
  ipcMain.handle(CH.appOpenLicenses, async () => {
    // generated by `npm run build` (scripts/licenses): outside the asar once packaged, so a
    // text viewer can open it in place; out/ in a development run
    const file = app.isPackaged
      ? join(process.resourcesPath, 'THIRD_PARTY_NOTICES.txt')
      : join(__dirname, '..', 'THIRD_PARTY_NOTICES.txt')
    if (!existsSync(file)) return 'The notices are written by `npm run build` — run it once, then try again.'
    return (await shell.openPath(file)) || null
  })
  ipcMain.handle(CH.shellOpen, (_e, url: string) => {
    const external = externalUrl(url)
    return external ? shell.openExternal(external) : Promise.resolve()
  })
  // the level is the user's, so it outlives the window: main restores it next launch
  // before the first paint, which is also when it needs it to size the window
  ipcMain.handle(CH.windowZoom, (_e, factor: number) => setZoom(applyWindowFloor(Number(factor))))

  ipcMain.handle(CH.updatesGet, () => updates.current)
  ipcMain.handle(CH.updatesCheck, () => updates.check())
  ipcMain.handle(CH.updatesDownload, () => updates.download())
  // the restart is an app.quit(): will-quit stops the turns and saves the index
  ipcMain.handle(CH.updatesInstall, (_e, req: unknown) =>
    updates.install({
      runningTurns: s.chat.runningTurns(),
      stopRunning: (req as { stopRunning?: unknown } | undefined)?.stopRunning === true
    })
  )
  ipcMain.handle(CH.updatesPrefs, () => updates.currentPrefs)
  ipcMain.handle(CH.updatesSetPrefs, (_e, prefs: UpdatePrefs) => updates.setPrefs(setUpdatePrefs(prefs)))

  ipcMain.handle(CH.attentionPrefs, () => desk.currentPrefs)
  ipcMain.handle(CH.attentionSetPrefs, (_e, prefs: AttentionPrefs) => {
    const saved = setAttentionPrefs(prefs)
    desk.setPrefs(saved)
    // the cleanup switch starts or stands down the daily check
    s.reminder.reschedule()
    return saved
  })
  ipcMain.handle(CH.attentionTest, () => desk.test())
  ipcMain.handle(CH.attentionPlay, (_e, tone: unknown) => desk.play(asAttentionTone(tone)))
  ipcMain.handle(CH.attentionFocus, (_e, focus: unknown) => desk.setFocus(asAttentionFocus(focus)))
  ipcMain.handle(CH.attentionLandings, () => desk.landings())
  ipcMain.handle(CH.attentionCleanup, () => desk.cleanupNotice())
  ipcMain.handle(CH.attentionTakeOpen, () => takePendingOpen())
}
